Models/Seller.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CaseStudy.Models
{
    public class Seller
    {
       [Key]
        public int SID { get; set; }
        public string Sname { get; set; }
        public string Companyname { get; set; }
        public string Semail { get; set; }
        public string Spassword { get; set; }
        public string Saddress { get; set; }
        public int Contactno { get; set; }
        public string PhotoPath { get; set; }

    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using CaseStudy.Models;

namespace CaseStudy.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/SellerController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using CaseStudy.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace CaseStudy.Controllers
{
    public class SellerController : Controller
    {
        // GET: Seller

        private readonly SellerContext _context;
        private readonly IWebHostEnvironment hostingEnvironment;
        public SellerController(SellerContext context, IWebHostEnvironment hostingEnvironment)
        {
            this._context = context;
            this.hostingEnvironment = hostingEnvironment;
        }
        public ActionResult Home()
        {
            return View();
        }
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult SellerRegister()
        {
            return View();
        }
        [HttpPost]
        public ActionResult SellerRegister(SellerCreateView model)
        {
            if (ModelState.IsValid)
            {
                string uniqueFileName = null;

                // If the Photo property on the incoming model object is not null, then the user
                // has selected an image to upload.
                if (model.Photopath != null)
                {
                    // The image must be uploaded to the images folder in wwwroot
                    // To get the path of the wwwroot folder we are using the inject
                    // HostingEnvironment service provided by ASP.NET Core
                    string uploadsFolder = Path.Combine(hostingEnvironment.WebRootPath, "images");
                    // To make sure the file name is unique we are appending a new
                    // GUID value and and an underscore to the file name
                    uniqueFileName = Guid.NewGuid().ToString() + "_" + model.Photopath.FileName;
                    string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                    // Use CopyTo() method provided by IFormFile interface to
                    // copy the file to wwwroot/images folder
                    model.Photopath.CopyTo(new FileStream(filePath, FileMode.Create));
                }

                Seller sel = new Seller
                {
                    Sname = model.Sname,
                    Spassword = model.Spassword,
                    Companyname = model.Companyname,
                    Saddress = model.Saddress,
                    Contactno = model.Contactno,
                    Semail = model.Semail,
                    SID = model.SID,

                    // Store the file name in PhotoPath property of the employee object
                    // which gets saved to the Employees database table
                    PhotoPath = uniqueFileName
                };

                _context.Add(sel);
                _context.SaveChanges();
                return RedirectToAction("Details", new { id = sel.SID});
            }
                 return View();

        }
        public ActionResult Details(int id)
        {
            Seller sel = _context.Sellers.FirstOrDefault(e => e.SID == id);
            return View(sel);
        }

        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Login(Seller sel)
        {
            var loginuser = _context.Sellers.Where(e => e.Sname ==sel.Sname&& e.Spassword ==sel.Spassword).ToList();
            if (loginuser.Count == 0)
            {
                ViewBag.message = "not valid";
                return View();

            }
            else
            {

                HttpContext.Session.SetString("SName",sel.Sname);
                Response.Cookies.Append("lastLogin", DateTime.Now.ToString());
                HttpContext.Session.SetString("llogin", DateTime.Now.ToString());

                return RedirectToAction("SellerDashBoard");

            }
        }
        public ActionResult SellerDashBoard()
        {
            if (HttpContext.Session.GetString("SName") != null)
            {

                ViewBag.Sname = HttpContext.Session.GetString("SName").ToString();
                ViewBag.lldt = HttpContext.Session.GetString("llogin").ToString();
                return View();
            }
            if (Request.Cookies["lastlogin"] != null)
            {
                ViewBag.lld = Request.Cookies["lastlogin"].ToString();
                return View();
            }
            return View();
        }
        public ActionResult logout()
        {
            Response.Cookies.Append("lastlogin", DateTime.Now.ToString());
            HttpContext.Session.Clear();
            return RedirectToAction("Login");
        }





        // GET: Seller/Details/5
        public ActionResult Create()
        {
            return View();
        }

        // GET: Seller/Create
       

        // POST: Seller/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Seller/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Seller/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Seller/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Seller/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Views/Seller/Details.cshtml
@model CaseStudy.Models.Seller

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
var photoPath = "~/images/" + (Model.PhotoPath ?? "targeting.png");
}

<h1>Details</h1>

<div>
    <h4>Seller</h4>
    <hr />

    <div class="card-deck">
      
        <div class="card m-3" style="min-width: 18rem; max-width:30.5%;">
            <div class="card-header">
                <h3>@Model.Sname</h3>



            </div>
            <div class="card-body">

            
            <img class="card-img-top imageThumbnail" src="@photoPath"
                 asp-append-version="true" />
            <h3>@Model.Semail</h3>
            <h3>@Model.Saddress</h3>
            <h3>@Model.Contactno</h3>
            </div>
            <div class="card-footer text-center">
                <a asp-controller="home" asp-action="details" asp-route-id="@Model.SID" class="btn btn-primary m-1">View</a>
                <a href="#" class="btn btn-primary m-1">Edit</a>
                <a href="#" class="btn btn-danger m-1">Delete</a>
            </div>
        </div>
        }
    </div>
</div>

Views/Seller/Home.cshtml

@{
    ViewData["Title"] = "Home";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<div style="background-color:deepskyblue">
    <h1>Home</h1>
    <table cellpadding="2">
        <tr>
            <td class="jumbotron" style="background-color:blueviolet">
                <a href="~/Buyer/Login"> <h1>Buyer</h1>&nbsp;&nbsp; </a>
            </td>
        </tr>
        <tr>
            <td class="jumbotron" style="background-color:aqua">
                <a href="~/Seller/Login"> <h1>Seller</h1>&nbsp;&nbsp; </a>
            </td>
        </tr>
        <tr>
            <td class="jumbotron" style="background-color:mediumspringgreen"><a href="~/Buyer/Login"> <h1>Admin</h1>&nbsp;&nbsp; </a></td>
        </tr>

    </table>



    </div>

Views/Seller/Login.cshtml
@model CaseStudy.Models.Seller

@*@{
    ViewData["Title"] = "Login";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}*@

<h1>Login</h1>

<h4>Seller</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Login">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Sname" class="control-label"></label>
                <input asp-for="Sname" class="form-control" />
                <span asp-validation-for="Sname" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <label asp-for="Spassword" class="control-label"></label>
                <input asp-for="Spassword" class="form-control" />
                <span asp-validation-for="Spassword" class="text-danger"></span>
            </div>
            
            
            <div class="form-group">
                <input type="submit" value="Login" class="btn btn-primary" />
            </div>
            <div>
                <h5 class="text-danger">@ViewBag.message</h5>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Seller/SellerDashBoard.cshtml

@*@{
    ViewData["Title"] = "SellerDashBoard";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}*@

<h1>SellerDashBoard</h1>
<h1 class="text-danger">@ViewBag.SName</h1>
<h1 class="text-danger">@ViewBag.lldt</h1>
<h1 class="text-danger">@ViewBag.lld</h1>
<h4 class="align-text-top text-danger"><a asp-action="Login" asp-controller="Seller">logout</a></h4>

Views/Seller/SellerRegister.cshtml
@model CaseStudy.Models.SellerCreateView

@{
    ViewData["Title"] = "SellerRegister";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>SellerRegister</h1>

<h4>Seller</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form enctype="multipart/form-data" asp-action="SellerRegister">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Sname" class="control-label"></label>
                <input asp-for="Sname" class="form-control" />
                <span asp-validation-for="Sname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Companyname" class="control-label"></label>
                <input asp-for="Companyname" class="form-control" />
                <span asp-validation-for="Companyname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Semail" class="control-label"></label>
                <input asp-for="Semail" class="form-control" />
                <span asp-validation-for="Semail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Spassword" class="control-label"></label>
                <input asp-for="Spassword" class="form-control" />
                <span asp-validation-for="Spassword" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Saddress" class="control-label"></label>
                <input asp-for="Saddress" class="form-control" />
                <span asp-validation-for="Saddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Contactno" class="control-label"></label>
                <input asp-for="Contactno" class="form-control" />
                <span asp-validation-for="Contactno" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Photopath" class="control-label"></label>
                <div class="col-sm-10">
                    <div class="custom-file">
                        <input asp-for="Photopath" class="form-control custom-file-input" />
                        <label class="custom-file-label">Choose File...</label>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
            @section Scripts {
                <script>
            $(document).ready(function () {
                $('.custom-file-input').on("change", function () {
                    var fileName = $(this).val().split("\\").pop();
                    $(this).next('.custom-file-label').html(fileName);
                });
            });
                </script>
            }
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>
