Models/Buyer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CaseStudy.Models
{
    public class Buyer
    {
        [Key]
        public int BId { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Mail { get; set; }
        public int Phoneno { get; set; }
        public string Password { get; set; }
        public DateTime CreatedDate { get; set; }
    }
}

Controllers/BuyerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CaseStudy.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace CaseStudy.Controllers
{
    public class BuyerController : Controller
    {
        public readonly BuyerContext _context;
        public BuyerController(BuyerContext context)
        {
            this._context = context;

        }
        public ActionResult Index()
        {
             return View();
        }

        // GET: Buyer
        [HttpGet]
        public ActionResult BuyerRegister()
        {
            return View();
        }
        [HttpPost]
        public ActionResult BuyerRegister(Buyer buy)
        {
            try
            {
                _context.Add(buy);
                _context.SaveChanges();
                ViewBag.message = buy.Name + "  registration successful";
                return View();
            }
            catch (Exception e)
            {
                ViewBag.message =buy.Name  + "  registration failed ";
                return View();
            }

        }
        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(Buyer buy)
        {
            var loginuser = _context.Buyers.Where(e => e.Name == buy.Name && e.Password == buy.Password).ToList();
            if (loginuser.Count == 0)
            {
                ViewBag.message = "not valid";
                return View();

            }
            else
            {
                HttpContext.Session.SetString("Name",buy.Name);
                Response.Cookies.Append("lastLogin",DateTime.Now.ToString());
                HttpContext.Session.SetString("lastlogin", DateTime.Now.ToString());

                return RedirectToAction("DashBoard");
               
            }
        
        }

        public ActionResult DashBoard()
        {
            if (HttpContext.Session.GetString("Name") != null)
            {

                ViewBag.Bname = HttpContext.Session.GetString("Name").ToString();
                ViewBag.lldt = HttpContext.Session.GetString("lastlogin").ToString();
                return View();
            }
            if (Request.Cookies["lastlogin"] != null)
            {
                ViewBag.lldt = Request.Cookies["lastlogin"].ToString();
                return View();
            }
            return View();
        }
        public ActionResult logout()
        {
            Response.Cookies.Append("lastlogin",DateTime.Now.ToString());
            HttpContext.Session.Clear();
            return RedirectToAction("Login");
        }

        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Buyer/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Buyer/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Buyer/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Buyer/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Buyer/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Buyer/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Views/Buyer/BuyerRegister.cshtml
@model CaseStudy.Models.Buyer

@*@{
    ViewData["Title"] = "BuyerRegister";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}*@

<h1>BuyerRegister</h1>

<h4>Buyer</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="BuyerRegister">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Mail" class="control-label"></label>
                <input asp-for="Mail" class="form-control" />
                <span asp-validation-for="Mail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phoneno" class="control-label"></label>
                <input asp-for="Phoneno" class="form-control" />
                <span asp-validation-for="Phoneno" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreatedDate" class="control-label"></label>
                <input asp-for="CreatedDate" class="form-control" />
                <span asp-validation-for="CreatedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Buyer/DashBoard.cshtml

@*@{
    ViewData["Title"] = "DashBoard";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}*@

<h1>DashBoard</h1>

<h1 class="text-danger">@ViewBag.BName</h1>
<h1 class="text-danger">@ViewBag.lldt</h1>
<h4 class="align-text-top text-danger"><a asp-action="Login"  asp-controller="Buyer">logout</a></h4>

Views/Buyer/Login.cshtml
@model CaseStudy.Models.Buyer

@{
    ViewData["Title"] = "Login";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<h1>Login</h1>

<h4>Buyer</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Login">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
          
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Login" class="btn btn-primary" />
            </div>
            <div>
                @ViewBag.message
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}